project:
  type: website
  output-dir: "docs"
website:
  title: "Ingmar Visser"
  navbar:
    left:
      - href: index.qmd
        text: About
      - markdown.qmd
      - posts.qmd
      - papers.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

