project:
  type: website
  output-dir: "docs"
website:
  title: "Ingmar Visser"
  navbar:
    left:
      - href: index.qmd
        text: about
      #- markdown.qmd
      - href: posts.qmd
        text: blog
      - papers.qmd
      - href: cvIngmarVisser.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

